### ISSUE TITLE
Whenever i use fs and snekfetch to fetch a file and write it as a JSOn. I get 405 Method not allowed.

### ISSUE THREAD

**Issue by ghost** [devsnek/snekfetch#10]
My code:
client.on('message', message => {
	if (message.content === '!catfact') {
		snekfetch.post('https://catfact.ninja/fact')
		.then(r => fs.writeFile('fact.json', r.body))
	}
});

Installed packages: discord.js, snekfetch

**Comment by devsnek** [comment]
No

**Comment by ghost** [comment]
Excuse me? I'm genuinely confused.

**Comment by devsnek** [comment]
i won't teach you how to code, but all of that is wrong, and not an issue with the library

**Comment by ghost** [comment]
What's wrong? New to this, self taught :/
