### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by devsnek** [devsnek/snekfetch#13]
This project needs proper tests.

Travis + Comprehensive tests are what this issue requires

If you can do this plz open a pr to the testing branch of this repo

**Comment by evan-007** [comment]
Any thoughts/opinions on test setup/tooling?

**Comment by devsnek** [comment]
@evan-007 i'm ok with whatever as long as its sane and comprehensive

**Comment by ppsmirnov** [comment]
@devsnek can I take this?

**Comment by devsnek** [comment]
@ppsmirnov feel free, consider it a race to get a pr
