### ISSUE TITLE
Snekfetch can break if unexpected 'http2' module is found

### ISSUE THREAD

**Issue by masonlee** [devsnek/snekfetch#21]
Snekfetch version or commit hash:
v3.3.4

Explanation of issue:
The Snekfetch internal code tries to optionally requires 'http2', but the Snekfetch package does not list http2 as a dependency. Because of this, it is possible for Snekfetch to load an unexpected version of http2, and this can cause a crashing error at snekfetch/src/node/transports/http2.js:21

Example code to reproduce:

You can reproduce this by creating a new node 8.6 project with snekfetch and the popular parse-server module, which installs its own http2 module that is incompatible with what snekfetch expects.
```
"dependencies": {
   "parse-server": "2.6.3"
   ...
  }
```

When you cause Snekfetch to load, you should see this error:
```
~/project/node_modules/snekfetch/src/node/transports/http2.js:21
} = http2.constants;
          ^
TypeError: Cannot match against 'undefined' or 'null'.
  at Object.<anonymous> (~/project/node_modules/snekfetch/src/node/transports/http2.js:21:10)
  at Module._compile (module.js:624:30)
  at Object.Module._extensions..js (module.js:635:10)
  at Module.load (module.js:545:32)
```

- [ ] Issue occurs in browser
- [X] Issue occurs in node

**Comment by devsnek** [comment]
fixed in 0f404fc
