### ISSUE TITLE
Get request fails when URL contains weird characters like í, Ø, or ƒ

### ISSUE THREAD

**Issue by PeterGerma** [devsnek/snekfetch#23]
Snekfetch version or commit hash: "snekfetch": "^3.5.0"

Explaination of issue:
snekfetch.get breaks if the url contains weird characters.

**Comment by devsnek** [comment]
fixed before you opened this by 3.5.1

**Comment by PeterGerma** [comment]
Why are requests failing with accents when they are valid urls?

**Comment by devsnek** [comment]
@HeartInWork can you provide a test case that fails on the master branch

**Comment by HeartInWork** [comment]
```javascriptlet api = `https://na1.api.riotgames.com/lol/summoner/v3/summoners/by-name/${summoner}?api_key=${config.RiotAPIKey}`;
        
        snekfetch.get(api).then(r => {
```

**Comment by PeterGerma** [comment]
`let api = `https://na1.api.riotgames.com/lol/summoner/v3/summoners/by-name/${summoner}?api_key=${config.RiotAPIKey}`;`

Fails when summoner is Øsama, even though i can got directly to the URL from my browser and see the .json info

**Comment by devsnek** [comment]
@HeartInWork can you find an example that i can test without needing to sign up for some service and use api keys

**Comment by devsnek** [comment]
ok this should work in f7b4e10 but you must encode the url yourself (see https://www.google.com/search?q=javascript+encode+url&oq=javascript+encode+url)

**Comment by PeterGerma** [comment]
Thanks.  Do you think its possible for you to add more detailed examples to your documentation.  Specifically how you would handle errors?
