### ISSUE TITLE
TypeError: this is not a constructor

### ISSUE THREAD

**Issue by Ssaely** [devsnek/snekfetch#24]
Snekfetch version or commit hash:
3.6.0

Explaination of issue:
I updated Snekfetch to the latest version today and now, whenever I make a get request to an api, it sends an error.
```js
TypeError: this is not a constructor
    at runMethod (C:\USER\node_modules\snekfetch\src\index.js:265:12)
at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Example code to reproduce:
```js
const request = await get('http://api.urbandictionary.com/v0/define?term=' + encodeURIComponent(args.word));
```

- [ ] Issue occurs in browser
- [X] Issue occurs in node

**Comment by ShayBox** [comment]
Gus fixed it 5 hours ago but he hasn't pushed it to npm yet, install via github:devsnek/snekfetch for a temporary fix if you'd like
