### ISSUE TITLE
Missing node folder inside node_modules/snekfetch/src/

### ISSUE THREAD

**Issue by TiagoPortfolio** [devsnek/snekfetch#26]
Snekfetch version or commit hash:
3.6.4

Explaination of issue:
After doing npm install, only index.js file is in /node_modules/snekfetch/src/. So some files are missing and the folder "node" is missing aswell giving an error whenever I run my app.

Error: Cannot find module './node'
...
/app/node_modules/snekfetch/src/index.js:3:52

- [ ] Issue occurs in browser
- [x] Issue occurs in node

**Comment by devsnek** [comment]
cannot repro, seems like you messed it up

**Comment by TiagoPortfolio** [comment]
That was fast
