### ISSUE TITLE
Always try to parse the response for json

### ISSUE THREAD

**Issue by mikuhl-dev** [devsnek/snekfetch#27]
Snekfetch does a good job at automatically parsing json for most requests, but there are some which it doesn't parse. (Assuming its ones without content type as json.) I think it would be nice to always try to parse the response and then return the original content if it fails.

**Comment by devsnek** [comment]
never gonna happen, snekfetch will use content type and nothing else. take it up with the maintainer of the api, or manually JSON.parse(response.text)

**Comment by mikuhl-dev** [comment]
@devsnek could you at least use 'text/json' as another way to see if the response is json, a few websites are giving me this nowadays.

**Comment by devsnek** [comment]
no
