### ISSUE TITLE
API Permissions Missing Permissions Error, and 400 Bad Request Error

### ISSUE THREAD

**Issue by BannerBomb** [devsnek/snekfetch#28]
Snekfetch version or commit hash: 3.6.4

Explaination of issue:
[Issue with stack trace](http://prntscr.com/ihkoo2) I get this error logged about every few minutes.

Example code to reproduce:
```js
I do not know because the stack trace does not give any specific files but the snekfetch file.
```

- [ ] Issue occurs in browser
- [x] Issue occurs in node

**Comment by devsnek** [comment]
this has nothing to do with snekfetch
