### ISSUE TITLE
Switching OS?

### ISSUE THREAD

**Issue by darbyjack** [devsnek/snekfetch#29]
Snekfetch version or commit hash:
snekfetch@4.0.0-rc.0

Explaination of issue:
Was using Snekfetch just fine via node on Ubuntu, but after switching to Debian, it crashes when I try to start a script that uses the Snekfetch in it.

Example code to reproduce:
```js
// code here
```

Error:
(node) ExperimentalWarning: The http2 module is an experimental API.
/home/script/node_modules/snekfetch/src/node/index.js:93
options.connection.close();

TypeError: options.connection.close is not a function
at Unzip.stream.once (/home/script/node_modules/snekfetch/src/node/index.js:93:30)

- [ ] Issue occurs in browser
- [X] Issue occurs in node

**Comment by darbyjack** [comment]
I'll add that this was fixed by downgrading back to 3.6.1

**Comment by devsnek** [comment]
you'll need a more recent version of node, and btw RC.0 means release candidate
