### ISSUE TITLE
can't install latest version `404`

### ISSUE THREAD

**Issue by BannerBomb** [devsnek/snekfetch#32]
## Version or commit hash:
snekfetch@4.0.0-beta.0

## Explanation of issue:
When I try to update using `npm i snekfetch@4.0.0-beta.0` it returns 404, the only way I can update it is with `npm uninstall snekfetch` `npm i snekfetch` but it still tells me it is outdated and is wanting `4.0.0-rc.0`

## Example code to reproduce:
```js
// code here
```

- [ ] Issue occurs in browser
- [x] Issue occurs in node

**Comment by chickaletta1** [comment]
npm install snekfetch --save
