### ISSUE TITLE
Having an issue with formdata requests

### ISSUE THREAD

**Issue by dustinrouillard** [devsnek/snekfetch#33]
## Version or commit hash:
4.0.0-beta.0

## Explanation of issue:
So after a bit of messing about with this I've just about given up trying to make it work, I have a request I need to send formdata with and trying everything from the docs seems to return nothing I can get to work.

I've tried
`.send({ "field-1": "value", "field-2": "value" })`
`('url', { data: { "field-1": "value", "field-2": "value" } })`

Plus I've tried adding it directly to the url using
`URL?field-1=value&field-2=value`

All of these methods work in postman and my install of curl also with the npm module request.

This seems to be an issue with form names that have a hyphen in them, because I have another request that does not contain hyphens to the same api and it works just fine with the .send option.

## Example code to reproduce:
```js
snek.post('url').send({ "field-1": "value", "field-2": "value" }).then((body) => {
  console.log(resp.body);
});
```

- [ ] Issue occurs in browser
- [x] Issue occurs in node

**Comment by devsnek** [comment]
`.send` isn't for form data, use `.attach`

**Comment by dustinrouillard** [comment]
I know you closed this, but something tells me this is not my wrong doing as I'm logging into the same website with `.send` here 

```js
snek.post('https://solder.tetranite.com/login', { redirect: false }).send({
    email: config.solder.email,
    password: config.solder.pass
})
```

And that above code works as intended and it's also done with formdata.
But it doesn't have hypens in the url or the formdata.

I tried this below code and all of it doesn't contain formdata once it reaches the api.

```js
snek.post('https://solder.tetranite.com/mod/add-version?mod-id=163&mod-version=1.2.4').set('x-requested-with', 'XMLHttpRequest')
```

```js
snek.post('https://solder.tetranite.com/mod/add-version).set('x-requested-with', 'XMLHttpRequest').send({ 'mod-id': '163', 'mod-version': '1.2.4' })
```

```js
snek.post('https://solder.tetranite.com/mod/add-version').set('x-requested-with', 'XMLHttpRequest').attach('mod-id', '163').attach('mod-version', `1.2.4`)
```

None of these actually contain formdata once they reach the api. Even the URL with the formdata at the end of it works in the request module and also postman. Something makes me think that something is up with urls and/or formdata containing hypens

**Comment by devsnek** [comment]
`send` will send either a JSON or x-www-form-urlencoded body (if you explicitly set the content type to `application/x-www-form-urlencoded`)

`attach` will send a "Form Data" (`multipart/form-data`) body

when you say "formdata" do you mean a form-urlencoded body? please be more explicit about your issue.

also when trying to debug you can try `POST`ing to `https://httpbin.org/post` which will respond with whatever you send it

**Comment by dustinrouillard** [comment]
Alright, thanks for the info. I tested all the methods again with that url and it seems they're all detected, so it's just oddly not working with snekfetch for some reason. Thanks for your time.

**Comment by devsnek** [comment]
please paste a short snippet which i can run without changing anything that will demonstrate this bug

**Comment by dustinrouillard** [comment]
The request requires authentication, I can DM it to you on Discord if you'd rather.

**Comment by devsnek** [comment]
if you can't reproduce it with httpbin then it isn't a bug with snekfetch
