### ISSUE TITLE
snekfetch.get("url").response.text/body doesn't work

### ISSUE THREAD

**Issue by krisppurg** [devsnek/snekfetch#34]
snekfetch.get("url").response.text/body doesn't work. whenever I do a request (snekfetch.get("insert url here").response.text or snekfetch.get("insert url here").response.body), parse the thing and do something like this for example 
```js
snekfetch.get(`https://random.birb.pw/tweet`).response.body // Cannot get body of undefined
```

**Comment by devsnek** [comment]
it's a promise:
```js
snekfetch.get('https://random.birb.pw/tweet')
  .then((response) => {
    console.log(response.text);
  });
```

**Comment by krisppurg** [comment]
hm, but why does response exist?
