### ISSUE TITLE
Cannot send urlencoded data in options with the header at the same time

### ISSUE THREAD

**Issue by mikuhl-dev** [devsnek/snekfetch#35]
## Version or commit hash:

latest

## Explanation of issue:

This line of code gets the header:
https://github.com/devsnek/snekfetch/blob/75549220a44e03d889034b24ff5a4385ed7d52f5/src/index.js#L115
but returns undefined even though I obviously set it below, both the lowercase and capitalized versions does not work.
So then it overrides my content type, and sending json instead.

## Example code to reproduce:
```js
snekfetch.post(url, {
	headers: {
		'content-type': 'application/x-www-form-urlencoded'
	},
	data: {
		foo: 'bar',
		lorem: 'ipsum'
	}
}).then(response => {
	console.log(response.request.getHeader('content-type')) //application/json
})
```

occurs in node

**Comment by mikuhl-dev** [comment]
Actually, the line of code I referenced is different in my version, using getHeader, but I have the newest version, is the new code version not on npm?

EDIT: Installed directly from github, the line returns undefined anyway. Issue still remains.

EDIT: Nevermind, my Object.assign was removing the header, I'm sorry! 😢

**Comment by devsnek** [comment]
@MichaelPriebe is this still a bug?

**Comment by mikuhl-dev** [comment]
It was not even a bug I'm sorry, my class I used for everything was removing the headers because I didn't understand how Object.assign worked exactly. My bad! But thank you for fixing the Zlib error!
