### ISSUE TITLE
Create a changelog in which we can see breaking changes

### ISSUE THREAD

**Issue by wasdennnoch** [devsnek/snekfetch#37]
Hi,

this is not a code issue with the library but rather an issue with users updating. 2 months ago, in v4, you pushed updates which modified the response object, changing `res.status` to `res.statusCode`. This obviously breaks any application looking directly for the status code and when updating dependencies there is no changelog which lists all the breaking changes snekfetch v4 had (or at least I can't find one) which means that developers have no way of knowing that they have to change their request processing.  
The only way to know is by looking through the individual commit diffs (the commit descriptions aren't helping either) which takes time and is error-prone.

Please consider adding a `changelog.md` or a similar way to document changes which may impact applications using this package such as the one described above.

**Comment by devsnek** [comment]
@wasdennnoch i'll consider putting one together. also just for the record, v4 came out a few days ago, not 2 months ago
