### ISSUE TITLE
Error: 403 This host is not accessible

### ISSUE THREAD

**Issue by harrisonhoward** [devsnek/snekfetch#40]
## Version or commit hash:
v4.0.0

## Explanation of issue:
Crash Upon Start Up

Error: 403 This host is not accessible.
at _response.transport.request.then (/root/forbidden-bot/node_modules/snekfetch/src/index.js:182:21)

- [x] Issue occurs in node

## Notes
I use Snekfetch for my Discord Bot. I just recently moved to a new vps with Ubuntu and I just started getting this error and I have no idea why.

**Comment by devsnek** [comment]
the server is returning 403 to whatever request you are sending, that has nothing to do with snekfetch.
