### ISSUE TITLE
Unable to download & parse JAR file?

### ISSUE THREAD

**Issue by FireController1847** [devsnek/snekfetch#42]
## Version or commit hash:
4.0.2

## Explanation of issue:
I'm not sure if this is an issue with the way I'm doing this, but I cannot seem to download a jar file, and then write it to a file using fs. Here's the example code below.

I know for a fact that the URL below works fine, because when I open the JAR after I download it via chrome using 7-zip, it opens fine. When I open it after a snekfetch download, though, it errors. 

## Example code to reproduce:
```js
request.get('https://libraries.minecraft.net/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar').then(r => fs.writeFileSync('./mything.jar', r.body));
```

- [ ] Issue occurs in browser
- [x] Issue occurs in node

**Comment by FireController1847** [comment]
Actually, I apologise for this issue. I believe this is an issue with the way I'm requesting/parsing the jar file. I've made a [stackoverflow question](https://stackoverflow.com/questions/50768524/how-to-download-and-write-a-jar-file-in-node-js) in hopes that'll help.

**Comment by FireController1847** [comment]
Actually, this works. I'm beginning to believe this is actually an issue with the library as I'm not sure if I'm just not able to get the raw data or set the encoding to raw.

```js
const request = require('request');
const fs = require('fs');

request.get('https://libraries.minecraft.net/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar', {
  encoding: null
}, function(e, r, b) {
  if (e) throw e;
  fs.writeFileSync('./mything2.jar', b);
});
```

Looking at the code, this may be a fundamental flaw of originally setting `body = ''` and then converting it back from a string to a buffer via raw. This is a wild guess though, I'm not sure how this library works.

**Comment by devsnek** [comment]
yes this is a known bug from an optimization I applied back in the 4.0.0 update. I'll fix it when I find some time.

**Comment by FireController1847** [comment]
Ah, okay
