### ISSUE TITLE
SnekfetchResponse=>Request is undefined

### ISSUE THREAD

**Issue by favna** [devsnek/snekfetch#44]
## Version or commit hash:  
All version >= 4.X

## Explanation of issue:  
The `request` property of the SnekfetchResponse object is consistently `undefined`

## Example code to reproduce:
```js
const request = require('snekfetch');

async function run() {
  const result = await request.get('https://google.com');
  return console.log(result);
}

run();
```

Output of this code:
```js
{ request: undefined,
  body: [Getter],
  raw: <Buffer 3c 21 64 6f 63 74 79 70 65 20 68 74 6d 6c 3e 3c 68 74 6d 6c 20 69 74 65 6d 73 63 6f 70 65 3d 22 22 20 69 74 65 6d 74 79 70 65 3d 22 68 74 74 70 3a 2f ... >,
  ok: true,
  headers:
   { date: 'Tue, 19 Jun 2018 19:16:28 GMT',
     expires: '-1',
     'cache-control': 'private, max-age=0',
     'content-type': 'text/html; charset=ISO-8859-1',
     p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
     'content-encoding': 'gzip',
     server: 'gws',
     'x-xss-protection': '1; mode=block',
     'x-frame-options': 'SAMEORIGIN',
     'set-cookie':
      [ '1P_JAR=2018-06-19-19; expires=Thu, 19-Jul-2018 19:16:28 GMT; path=/; domain=.google.com',
        'NID=132=Ch6wiNFG_I5ZerwxDOwEGSFIqZa8FQ-P8BvJhYpnbzeh-6bUxoYqbnPAzSjZqGrguiXut1uSaLCVyC3jvI3arRs21St9jJVrvYtIX7-M3abMkyMiTeyviGLEjZ8oRaIT; expires=Wed, 19-Dec-2018 19:16:28 GMT; path=/; domain=.google.com; HttpOnly' ],
     'alt-svc': 'quic=":443"; ma=2592000; v="43,42,41,39,35"',
     connection: 'close',
     'transfer-encoding': 'chunked' },
  statusCode: 200,
  statusText: 'OK' }
```

Example code also on runkit: https://runkit.com/favna/snekfech-issue-44

- [ ] Issue occurs in browser
- [X] Issue occurs in node

**Comment by favna** [comment]
I did some more digging through the differences in `src/index.js` between <= v4 and >= v4 and I found somewhat where the issue is caused.


Before there was this line in the constructor: `this.request = transport.buildRequest.call(this, method, url, opts);` and a total of 15 occurrences of `this.request` throughout the rest of the code, but currently it changes to a single occurrence (line 163) which is in the SnekfetchResponse object as what is assigned to `request`, thus it is obviously undefined.

Lines in question:

latest commit:
https://github.com/devsnek/snekfetch/blob/b0014a3109a64fde9dcd5b65a1a5d8b493d38fac/src/index.js#L162-L192

Commit c939e4fd5af8391dd4ebc627200698c739689519

https://github.com/devsnek/snekfetch/blob/c939e4fd5af8391dd4ebc627200698c739689519/src/index.js#L33-L47

https://github.com/devsnek/snekfetch/blob/c939e4fd5af8391dd4ebc627200698c739689519/src/index.js#L170-L205

It was the commit [http2 rewrite](https://github.com/devsnek/snekfetch/commit/a2810020191a309d505bb612b5a7833d3337f4e7#diff-1fdf421c05c1140f6d71444ea2b27638) (a2810020191a309d505bb612b5a7833d3337f4e7) that removed the `this.request` line from the constructor and other methods

**Comment by devsnek** [comment]
i intended for it to be completely removed. seems like there's still some legacy stuff lying around.

**Comment by favna** [comment]
The reason I started digging around is because the API for Discordbots.org is throwing 403 errors on snekfetch >= 4.x and the website devs cannot tell why this either (at least I Tonkku on discord pretty much said so). If we would have the full request output it might be possible to get somewhere with debugging the issue. 

Their API works just fine on snekfetch <= 4.x as well as libs such as request and build-in http.

I initially stumbled on the undefined issue while fixing my youtube command where I referenced whatever the request processed as my query through `res.request.query.q`. I fixed this by just changing it to message arg but with what you just said I'm not sure if you're saying you're going to fix the request property, or remove it altogether?

**Comment by devsnek** [comment]
@Favna yeah i removed it completely in v4. it was a design mistake. an instance of `Snekfetch` is itself the request, so having a request property was redundant.

fixed in 025d57918b0615ac403d613abe558ed53330580f

**Comment by MrJacz** [comment]
I'm currently using v4.0.4 and have never had that issue, not on 4.0.0, 4.0.1, 4.0.2 or 4.0.3.
The `request` prop was intended to be removed.

The error some people are getting is
```javascript
{ Error: 403 This host is not accessible.
    at _response.transport.request.then (.../node_modules/dblapi.js/node_modules/snekfetch/src/index.js:193:21) 
    at <anonymous> 
    at process._tickCallback (internal/process/next_tick.js:118:7) 
  request: undefined,
  body: body buffer here same as above,
  ok: false,
  headers:
   { date: 'Sun, 17 Jun 2018 01:10:17 GMT',
   A 'content-type': 'text/html; charset=utf-8',
   A 'transfer-encoding': 'chunked',
   A connection: 'close',
   A 'set-cookie':
   A  [ '__cfduid=d465203f15027ccdf72770b3674233f21529197817; expires=Mon, 17-Jun-19 01:10:17 GMT; path=/; domain=.discordbots.org;
pOnly; Secure' ],
   A 'x-varnish': '959250680',
   A 'retry-after': '5', 
   A 'strict-transport-tecuri-y': 'max-age=15552000;0includeSubDomains; preload', 
   A 'x-content-type-options': 'nosniff',  
     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 
     server: 'cloudflare',
     'cf-ray': '42c1a2b5dedc9fcc-IAD',
     'content-encoding': 'gzip' },
  statusCode: 403,
  statusText: 'This host is not accessible.' }
``` 
which to me seems like a cloudflare issue but people are only getting it with snekfetch?

**Comment by devsnek** [comment]
if you verify that the issue only happens with snekfetch open another issue here, this one is closed.
