### ISSUE TITLE
404 Not Found when trying to access website.

### ISSUE THREAD

**Issue by nesben** [devsnek/snekfetch#46]
## Version or commit hash:
4.0.4

## Explanation of issue:
I've been trying to use snekfetch to communicate with my api, but i keep getting "Error: 404 Not Found" even though the link is correct and I can access it in my browser.

## Example code to reproduce:
```js
const snek = require('snekfetch')

exports.run = function (message) {
    try {
        snek.get(`https://towardly-sum.000webhostapp.com/myAPI/dogapi/dogapi.php`).catch(err => console.log(err))
            .then(result => {
                console.log(result.body)
            });

    } catch (err) {
        console.log(err);
    }
};

exports.run();
```

- [ ] Issue occurs in browser
- [x] Issue occurs in node

**Comment by SamuraiStacks** [comment]
The version is 4.0.4 and when you remove the dots its 404 so what did you expect?
